name: Sync Master and Staging

on:
  pull_request:
    branches:
      - master
  
  push:
    branches:
      - master

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Fetch latest changes from remote
        run: |
          git fetch origin
          
      - name: Pull latest changes into staging branch
        run: |
          git checkout staging
          git pull origin staging

      - name: Merge changes from master to staging
        run: |
          git config user.name "GitHub Actions"
          git config user.email "hangout14@gmail.com"
          git merge origin/master --no-ff --no-edit
          git push
